import random

print("=" * 50)
print("WELCOME TO MASTERMIND!")
print("=" * 50)
print("")
print("THE ULTIMATE CODE-BREAKING CHALLENGE!")
print("")
print("Try to guess the secret combination of 4 numbers (1-6)")
print("You have 10 attempts to crack the code!")
print("")
print("FEEDBACK SYMBOLS:")
print("  * = Correct number in CORRECT position")
print("  - = Correct number in WRONG position")
print("")
print("=" * 50)
print("LET THE GAME BEGIN!")
print("=" * 50)
print("")
